insert into MOCK_DATA (id, course) values (1, 'Sales Representative');
insert into MOCK_DATA (id, course) values (2, 'Actuary');
insert into MOCK_DATA (id, course) values (3, 'Tax Accountant');
insert into MOCK_DATA (id, course) values (4, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (5, 'Web Developer II');
insert into MOCK_DATA (id, course) values (6, 'Research Nurse');
insert into MOCK_DATA (id, course) values (7, 'Accounting Assistant I');
insert into MOCK_DATA (id, course) values (8, 'Quality Engineer');
insert into MOCK_DATA (id, course) values (9, 'Database Administrator IV');
insert into MOCK_DATA (id, course) values (10, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (11, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (12, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (13, 'Social Worker');
insert into MOCK_DATA (id, course) values (14, 'Editor');
insert into MOCK_DATA (id, course) values (15, 'VP Sales');
insert into MOCK_DATA (id, course) values (16, 'Systems Administrator I');
insert into MOCK_DATA (id, course) values (17, 'Software Consultant');
insert into MOCK_DATA (id, course) values (18, 'Research Associate');
insert into MOCK_DATA (id, course) values (19, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (20, 'Web Designer IV');
insert into MOCK_DATA (id, course) values (21, 'Research Nurse');
insert into MOCK_DATA (id, course) values (22, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (23, 'Nurse');
insert into MOCK_DATA (id, course) values (24, 'Research Associate');
insert into MOCK_DATA (id, course) values (25, 'Programmer I');
insert into MOCK_DATA (id, course) values (26, 'Budget/Accounting Analyst IV');
insert into MOCK_DATA (id, course) values (27, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (28, 'Project Manager');
insert into MOCK_DATA (id, course) values (29, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (30, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (31, 'Editor');
insert into MOCK_DATA (id, course) values (32, 'Developer IV');
insert into MOCK_DATA (id, course) values (33, 'Analyst Programmer');
insert into MOCK_DATA (id, course) values (34, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (35, 'Biostatistician II');
insert into MOCK_DATA (id, course) values (36, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (37, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (38, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (39, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (40, 'Web Designer II');
insert into MOCK_DATA (id, course) values (41, 'Product Engineer');
insert into MOCK_DATA (id, course) values (42, 'Senior Editor');
insert into MOCK_DATA (id, course) values (43, 'Budget/Accounting Analyst II');
insert into MOCK_DATA (id, course) values (44, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (45, 'Professor');
insert into MOCK_DATA (id, course) values (46, 'Actuary');
insert into MOCK_DATA (id, course) values (47, 'Computer Systems Analyst III');
insert into MOCK_DATA (id, course) values (48, 'Tax Accountant');
insert into MOCK_DATA (id, course) values (49, 'Research Assistant III');
insert into MOCK_DATA (id, course) values (50, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (51, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (52, 'Financial Analyst');
insert into MOCK_DATA (id, course) values (53, 'VP Marketing');
insert into MOCK_DATA (id, course) values (54, 'VP Product Management');
insert into MOCK_DATA (id, course) values (55, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (56, 'Account Representative IV');
insert into MOCK_DATA (id, course) values (57, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (58, 'Food Chemist');
insert into MOCK_DATA (id, course) values (59, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (60, 'Human Resources Assistant IV');
insert into MOCK_DATA (id, course) values (61, 'Office Assistant III');
insert into MOCK_DATA (id, course) values (62, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (63, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (64, 'Statistician III');
insert into MOCK_DATA (id, course) values (65, 'Software Engineer III');
insert into MOCK_DATA (id, course) values (66, 'Paralegal');
insert into MOCK_DATA (id, course) values (67, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (68, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (69, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (70, 'Sales Representative');
insert into MOCK_DATA (id, course) values (71, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (72, 'Health Coach I');
insert into MOCK_DATA (id, course) values (73, 'Accountant II');
insert into MOCK_DATA (id, course) values (74, 'Research Associate');
insert into MOCK_DATA (id, course) values (75, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (76, 'Biostatistician I');
insert into MOCK_DATA (id, course) values (77, 'Web Developer II');
insert into MOCK_DATA (id, course) values (78, 'Sales Representative');
insert into MOCK_DATA (id, course) values (79, 'Geologist II');
insert into MOCK_DATA (id, course) values (80, 'Librarian');
insert into MOCK_DATA (id, course) values (81, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (82, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (83, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (84, 'Web Designer III');
insert into MOCK_DATA (id, course) values (85, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (86, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (87, 'Account Executive');
insert into MOCK_DATA (id, course) values (88, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (89, 'Junior Executive');
insert into MOCK_DATA (id, course) values (90, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (91, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (92, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (93, 'Project Manager');
insert into MOCK_DATA (id, course) values (94, 'Account Executive');
insert into MOCK_DATA (id, course) values (95, 'Tax Accountant');
insert into MOCK_DATA (id, course) values (96, 'Health Coach IV');
insert into MOCK_DATA (id, course) values (97, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (98, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (99, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (100, 'Programmer Analyst II');
insert into MOCK_DATA (id, course) values (101, 'Analyst Programmer');
insert into MOCK_DATA (id, course) values (102, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (103, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (104, 'Product Engineer');
insert into MOCK_DATA (id, course) values (105, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (106, 'Junior Executive');
insert into MOCK_DATA (id, course) values (107, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (108, 'Editor');
insert into MOCK_DATA (id, course) values (109, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (110, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (111, 'Director of Sales');
insert into MOCK_DATA (id, course) values (112, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (113, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (114, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (115, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (116, 'Health Coach III');
insert into MOCK_DATA (id, course) values (117, 'Software Engineer IV');
insert into MOCK_DATA (id, course) values (118, 'Systems Administrator IV');
insert into MOCK_DATA (id, course) values (119, 'Media Manager III');
insert into MOCK_DATA (id, course) values (120, 'Operator');
insert into MOCK_DATA (id, course) values (121, 'Safety Technician II');
insert into MOCK_DATA (id, course) values (122, 'Software Consultant');
insert into MOCK_DATA (id, course) values (123, 'Actuary');
insert into MOCK_DATA (id, course) values (124, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (125, 'Pharmacist');
insert into MOCK_DATA (id, course) values (126, 'Operator');
insert into MOCK_DATA (id, course) values (127, 'Nurse');
insert into MOCK_DATA (id, course) values (128, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (129, 'VP Product Management');
insert into MOCK_DATA (id, course) values (130, 'Editor');
insert into MOCK_DATA (id, course) values (131, 'Web Designer IV');
insert into MOCK_DATA (id, course) values (132, 'Systems Administrator IV');
insert into MOCK_DATA (id, course) values (133, 'Web Developer IV');
insert into MOCK_DATA (id, course) values (134, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (135, 'Design Engineer');
insert into MOCK_DATA (id, course) values (136, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (137, 'Editor');
insert into MOCK_DATA (id, course) values (138, 'Software Test Engineer II');
insert into MOCK_DATA (id, course) values (139, 'Software Test Engineer IV');
insert into MOCK_DATA (id, course) values (140, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (141, 'Junior Executive');
insert into MOCK_DATA (id, course) values (142, 'Account Executive');
insert into MOCK_DATA (id, course) values (143, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (144, 'Accounting Assistant I');
insert into MOCK_DATA (id, course) values (145, 'Administrative Assistant II');
insert into MOCK_DATA (id, course) values (146, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (147, 'Teacher');
insert into MOCK_DATA (id, course) values (148, 'Programmer Analyst III');
insert into MOCK_DATA (id, course) values (149, 'Financial Analyst');
insert into MOCK_DATA (id, course) values (150, 'Recruiter');
insert into MOCK_DATA (id, course) values (151, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (152, 'Actuary');
insert into MOCK_DATA (id, course) values (153, 'Human Resources Assistant II');
insert into MOCK_DATA (id, course) values (154, 'VP Product Management');
insert into MOCK_DATA (id, course) values (155, 'Librarian');
insert into MOCK_DATA (id, course) values (156, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (157, 'Research Associate');
insert into MOCK_DATA (id, course) values (158, 'Occupational Therapist');
insert into MOCK_DATA (id, course) values (159, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (160, 'Web Developer IV');
insert into MOCK_DATA (id, course) values (161, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (162, 'Actuary');
insert into MOCK_DATA (id, course) values (163, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (164, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (165, 'Structural Analysis Engineer');
insert into MOCK_DATA (id, course) values (166, 'Systems Administrator IV');
insert into MOCK_DATA (id, course) values (167, 'Software Test Engineer I');
insert into MOCK_DATA (id, course) values (168, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (169, 'Senior Editor');
insert into MOCK_DATA (id, course) values (170, 'VP Product Management');
insert into MOCK_DATA (id, course) values (171, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (172, 'Editor');
insert into MOCK_DATA (id, course) values (173, 'Senior Sales Associate');
insert into MOCK_DATA (id, course) values (174, 'Design Engineer');
insert into MOCK_DATA (id, course) values (175, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (176, 'Junior Executive');
insert into MOCK_DATA (id, course) values (177, 'Structural Analysis Engineer');
insert into MOCK_DATA (id, course) values (178, 'Budget/Accounting Analyst I');
insert into MOCK_DATA (id, course) values (179, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (180, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (181, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (182, 'Product Engineer');
insert into MOCK_DATA (id, course) values (183, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (184, 'Nurse');
insert into MOCK_DATA (id, course) values (185, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (186, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (187, 'Social Worker');
insert into MOCK_DATA (id, course) values (188, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (189, 'Account Coordinator');
insert into MOCK_DATA (id, course) values (190, 'Automation Specialist I');
insert into MOCK_DATA (id, course) values (191, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (192, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (193, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (194, 'Pharmacist');
insert into MOCK_DATA (id, course) values (195, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (196, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (197, 'General Manager');
insert into MOCK_DATA (id, course) values (198, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (199, 'Technical Writer');
insert into MOCK_DATA (id, course) values (200, 'Associate Professor');
insert into MOCK_DATA (id, course) values (201, 'Budget/Accounting Analyst IV');
insert into MOCK_DATA (id, course) values (202, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (203, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (204, 'Editor');
insert into MOCK_DATA (id, course) values (205, 'Technical Writer');
insert into MOCK_DATA (id, course) values (206, 'Office Assistant I');
insert into MOCK_DATA (id, course) values (207, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (208, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (209, 'Teacher');
insert into MOCK_DATA (id, course) values (210, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (211, 'Operator');
insert into MOCK_DATA (id, course) values (212, 'Librarian');
insert into MOCK_DATA (id, course) values (213, 'Operator');
insert into MOCK_DATA (id, course) values (214, 'Nurse');
insert into MOCK_DATA (id, course) values (215, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (216, 'Teacher');
insert into MOCK_DATA (id, course) values (217, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (218, 'Staff Accountant II');
insert into MOCK_DATA (id, course) values (219, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (220, 'Senior Editor');
insert into MOCK_DATA (id, course) values (221, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (222, 'Budget/Accounting Analyst III');
insert into MOCK_DATA (id, course) values (223, 'Web Developer I');
insert into MOCK_DATA (id, course) values (224, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (225, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (226, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (227, 'General Manager');
insert into MOCK_DATA (id, course) values (228, 'Accountant III');
insert into MOCK_DATA (id, course) values (229, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (230, 'Operator');
insert into MOCK_DATA (id, course) values (231, 'Geologist III');
insert into MOCK_DATA (id, course) values (232, 'Accountant I');
insert into MOCK_DATA (id, course) values (233, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (234, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (235, 'Junior Executive');
insert into MOCK_DATA (id, course) values (236, 'Programmer Analyst I');
insert into MOCK_DATA (id, course) values (237, 'Health Coach I');
insert into MOCK_DATA (id, course) values (238, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (239, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (240, 'Operator');
insert into MOCK_DATA (id, course) values (241, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (242, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (243, 'Account Coordinator');
insert into MOCK_DATA (id, course) values (244, 'Media Manager II');
insert into MOCK_DATA (id, course) values (245, 'Nurse Practicioner');
insert into MOCK_DATA (id, course) values (246, 'Staff Accountant I');
insert into MOCK_DATA (id, course) values (247, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (248, 'Staff Accountant IV');
insert into MOCK_DATA (id, course) values (249, 'Media Manager II');
insert into MOCK_DATA (id, course) values (250, 'Compensation Analyst');
insert into MOCK_DATA (id, course) values (251, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (252, 'Automation Specialist I');
insert into MOCK_DATA (id, course) values (253, 'Systems Administrator I');
insert into MOCK_DATA (id, course) values (254, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (255, 'Sales Representative');
insert into MOCK_DATA (id, course) values (256, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (257, 'VP Sales');
insert into MOCK_DATA (id, course) values (258, 'Account Coordinator');
insert into MOCK_DATA (id, course) values (259, 'Associate Professor');
insert into MOCK_DATA (id, course) values (260, 'Database Administrator IV');
insert into MOCK_DATA (id, course) values (261, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (262, 'Administrative Assistant IV');
insert into MOCK_DATA (id, course) values (263, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (264, 'VP Sales');
insert into MOCK_DATA (id, course) values (265, 'VP Product Management');
insert into MOCK_DATA (id, course) values (266, 'Paralegal');
insert into MOCK_DATA (id, course) values (267, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (268, 'Editor');
insert into MOCK_DATA (id, course) values (269, 'Professor');
insert into MOCK_DATA (id, course) values (270, 'VP Sales');
insert into MOCK_DATA (id, course) values (271, 'VP Accounting');
insert into MOCK_DATA (id, course) values (272, 'Recruiter');
insert into MOCK_DATA (id, course) values (273, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (274, 'Food Chemist');
insert into MOCK_DATA (id, course) values (275, 'Account Coordinator');
insert into MOCK_DATA (id, course) values (276, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (277, 'Sales Representative');
insert into MOCK_DATA (id, course) values (278, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (279, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (280, 'Social Worker');
insert into MOCK_DATA (id, course) values (281, 'Nurse');
insert into MOCK_DATA (id, course) values (282, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (283, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (284, 'Structural Analysis Engineer');
insert into MOCK_DATA (id, course) values (285, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (286, 'VP Accounting');
insert into MOCK_DATA (id, course) values (287, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (288, 'Web Developer IV');
insert into MOCK_DATA (id, course) values (289, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (290, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (291, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (292, 'Food Chemist');
insert into MOCK_DATA (id, course) values (293, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (294, 'Research Assistant IV');
insert into MOCK_DATA (id, course) values (295, 'Engineer IV');
insert into MOCK_DATA (id, course) values (296, 'Web Designer III');
insert into MOCK_DATA (id, course) values (297, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (298, 'Software Engineer I');
insert into MOCK_DATA (id, course) values (299, 'Systems Administrator IV');
insert into MOCK_DATA (id, course) values (300, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (301, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (302, 'Accountant IV');
insert into MOCK_DATA (id, course) values (303, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (304, 'Research Associate');
insert into MOCK_DATA (id, course) values (305, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (306, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (307, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (308, 'Food Chemist');
insert into MOCK_DATA (id, course) values (309, 'Budget/Accounting Analyst IV');
insert into MOCK_DATA (id, course) values (310, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (311, 'Structural Engineer');
insert into MOCK_DATA (id, course) values (312, 'Accountant II');
insert into MOCK_DATA (id, course) values (313, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (314, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (315, 'Engineer IV');
insert into MOCK_DATA (id, course) values (316, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (317, 'Editor');
insert into MOCK_DATA (id, course) values (318, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (319, 'Web Designer IV');
insert into MOCK_DATA (id, course) values (320, 'Research Nurse');
insert into MOCK_DATA (id, course) values (321, 'Structural Engineer');
insert into MOCK_DATA (id, course) values (322, 'Junior Executive');
insert into MOCK_DATA (id, course) values (323, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (324, 'Budget/Accounting Analyst III');
insert into MOCK_DATA (id, course) values (325, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (326, 'Programmer III');
insert into MOCK_DATA (id, course) values (327, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (328, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (329, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (330, 'Junior Executive');
insert into MOCK_DATA (id, course) values (331, 'Social Worker');
insert into MOCK_DATA (id, course) values (332, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (333, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (334, 'Nurse');
insert into MOCK_DATA (id, course) values (335, 'Junior Executive');
insert into MOCK_DATA (id, course) values (336, 'Technical Writer');
insert into MOCK_DATA (id, course) values (337, 'Programmer Analyst IV');
insert into MOCK_DATA (id, course) values (338, 'Technical Writer');
insert into MOCK_DATA (id, course) values (339, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (340, 'Librarian');
insert into MOCK_DATA (id, course) values (341, 'VP Product Management');
insert into MOCK_DATA (id, course) values (342, 'Quality Engineer');
insert into MOCK_DATA (id, course) values (343, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (344, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (345, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (346, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (347, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (348, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (349, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (350, 'Accountant II');
insert into MOCK_DATA (id, course) values (351, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (352, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (353, 'Geologist II');
insert into MOCK_DATA (id, course) values (354, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (355, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (356, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (357, 'Statistician II');
insert into MOCK_DATA (id, course) values (358, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (359, 'Teacher');
insert into MOCK_DATA (id, course) values (360, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (361, 'Developer III');
insert into MOCK_DATA (id, course) values (362, 'Statistician IV');
insert into MOCK_DATA (id, course) values (363, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (364, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (365, 'Senior Editor');
insert into MOCK_DATA (id, course) values (366, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (367, 'Software Test Engineer IV');
insert into MOCK_DATA (id, course) values (368, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (369, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (370, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (371, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (372, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (373, 'Design Engineer');
insert into MOCK_DATA (id, course) values (374, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (375, 'Engineer I');
insert into MOCK_DATA (id, course) values (376, 'Database Administrator III');
insert into MOCK_DATA (id, course) values (377, 'Food Chemist');
insert into MOCK_DATA (id, course) values (378, 'Software Consultant');
insert into MOCK_DATA (id, course) values (379, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (380, 'Sales Representative');
insert into MOCK_DATA (id, course) values (381, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (382, 'Sales Representative');
insert into MOCK_DATA (id, course) values (383, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (384, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (385, 'Software Engineer III');
insert into MOCK_DATA (id, course) values (386, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (387, 'Programmer III');
insert into MOCK_DATA (id, course) values (388, 'Engineer III');
insert into MOCK_DATA (id, course) values (389, 'Technical Writer');
insert into MOCK_DATA (id, course) values (390, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (391, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (392, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (393, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (394, 'Director of Sales');
insert into MOCK_DATA (id, course) values (395, 'Design Engineer');
insert into MOCK_DATA (id, course) values (396, 'Accountant III');
insert into MOCK_DATA (id, course) values (397, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (398, 'Account Representative II');
insert into MOCK_DATA (id, course) values (399, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (400, 'Librarian');
insert into MOCK_DATA (id, course) values (401, 'Systems Administrator IV');
insert into MOCK_DATA (id, course) values (402, 'Nurse');
insert into MOCK_DATA (id, course) values (403, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (404, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (405, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (406, 'Accountant I');
insert into MOCK_DATA (id, course) values (407, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (408, 'VP Accounting');
insert into MOCK_DATA (id, course) values (409, 'Biostatistician II');
insert into MOCK_DATA (id, course) values (410, 'Actuary');
insert into MOCK_DATA (id, course) values (411, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (412, 'Director of Sales');
insert into MOCK_DATA (id, course) values (413, 'Administrative Assistant I');
insert into MOCK_DATA (id, course) values (414, 'Project Manager');
insert into MOCK_DATA (id, course) values (415, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (416, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (417, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (418, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (419, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (420, 'Human Resources Assistant II');
insert into MOCK_DATA (id, course) values (421, 'Senior Sales Associate');
insert into MOCK_DATA (id, course) values (422, 'VP Marketing');
insert into MOCK_DATA (id, course) values (423, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (424, 'Safety Technician IV');
insert into MOCK_DATA (id, course) values (425, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (426, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (427, 'VP Product Management');
insert into MOCK_DATA (id, course) values (428, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (429, 'Software Consultant');
insert into MOCK_DATA (id, course) values (430, 'Engineer I');
insert into MOCK_DATA (id, course) values (431, 'Accounting Assistant II');
insert into MOCK_DATA (id, course) values (432, 'Professor');
insert into MOCK_DATA (id, course) values (433, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (434, 'Automation Specialist II');
insert into MOCK_DATA (id, course) values (435, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (436, 'Budget/Accounting Analyst I');
insert into MOCK_DATA (id, course) values (437, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (438, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (439, 'Account Coordinator');
insert into MOCK_DATA (id, course) values (440, 'VP Marketing');
insert into MOCK_DATA (id, course) values (441, 'Software Engineer III');
insert into MOCK_DATA (id, course) values (442, 'Occupational Therapist');
insert into MOCK_DATA (id, course) values (443, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (444, 'Librarian');
insert into MOCK_DATA (id, course) values (445, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (446, 'Account Executive');
insert into MOCK_DATA (id, course) values (447, 'Research Assistant II');
insert into MOCK_DATA (id, course) values (448, 'Teacher');
insert into MOCK_DATA (id, course) values (449, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (450, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (451, 'Administrative Assistant III');
insert into MOCK_DATA (id, course) values (452, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (453, 'Technical Writer');
insert into MOCK_DATA (id, course) values (454, 'Account Representative I');
insert into MOCK_DATA (id, course) values (455, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (456, 'Safety Technician II');
insert into MOCK_DATA (id, course) values (457, 'Accounting Assistant II');
insert into MOCK_DATA (id, course) values (458, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (459, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (460, 'Nurse Practicioner');
insert into MOCK_DATA (id, course) values (461, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (462, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (463, 'Engineer II');
insert into MOCK_DATA (id, course) values (464, 'Operator');
insert into MOCK_DATA (id, course) values (465, 'Financial Analyst');
insert into MOCK_DATA (id, course) values (466, 'Teacher');
insert into MOCK_DATA (id, course) values (467, 'Research Associate');
insert into MOCK_DATA (id, course) values (468, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (469, 'Web Designer IV');
insert into MOCK_DATA (id, course) values (470, 'Junior Executive');
insert into MOCK_DATA (id, course) values (471, 'VP Accounting');
insert into MOCK_DATA (id, course) values (472, 'Compensation Analyst');
insert into MOCK_DATA (id, course) values (473, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (474, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (475, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (476, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (477, 'Administrative Assistant I');
insert into MOCK_DATA (id, course) values (478, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (479, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (480, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (481, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (482, 'Accounting Assistant III');
insert into MOCK_DATA (id, course) values (483, 'Computer Systems Analyst III');
insert into MOCK_DATA (id, course) values (484, 'Senior Sales Associate');
insert into MOCK_DATA (id, course) values (485, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (486, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (487, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (488, 'Senior Editor');
insert into MOCK_DATA (id, course) values (489, 'Librarian');
insert into MOCK_DATA (id, course) values (490, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (491, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (492, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (493, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (494, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (495, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (496, 'Web Developer IV');
insert into MOCK_DATA (id, course) values (497, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (498, 'VP Accounting');
insert into MOCK_DATA (id, course) values (499, 'Product Engineer');
insert into MOCK_DATA (id, course) values (500, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (501, 'Research Assistant III');
insert into MOCK_DATA (id, course) values (502, 'Web Designer II');
insert into MOCK_DATA (id, course) values (503, 'Software Test Engineer II');
insert into MOCK_DATA (id, course) values (504, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (505, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (506, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (507, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (508, 'Paralegal');
insert into MOCK_DATA (id, course) values (509, 'Project Manager');
insert into MOCK_DATA (id, course) values (510, 'Structural Engineer');
insert into MOCK_DATA (id, course) values (511, 'Librarian');
insert into MOCK_DATA (id, course) values (512, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (513, 'Pharmacist');
insert into MOCK_DATA (id, course) values (514, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (515, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (516, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (517, 'Software Engineer II');
insert into MOCK_DATA (id, course) values (518, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (519, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (520, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (521, 'Account Representative I');
insert into MOCK_DATA (id, course) values (522, 'Social Worker');
insert into MOCK_DATA (id, course) values (523, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (524, 'General Manager');
insert into MOCK_DATA (id, course) values (525, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (526, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (527, 'Computer Systems Analyst I');
insert into MOCK_DATA (id, course) values (528, 'Paralegal');
insert into MOCK_DATA (id, course) values (529, 'Compensation Analyst');
insert into MOCK_DATA (id, course) values (530, 'Product Engineer');
insert into MOCK_DATA (id, course) values (531, 'Engineer IV');
insert into MOCK_DATA (id, course) values (532, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (533, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (534, 'Sales Associate');
insert into MOCK_DATA (id, course) values (535, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (536, 'Senior Cost Accountant');
insert into MOCK_DATA (id, course) values (537, 'Financial Analyst');
insert into MOCK_DATA (id, course) values (538, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (539, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (540, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (541, 'Accountant II');
insert into MOCK_DATA (id, course) values (542, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (543, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (544, 'Software Test Engineer IV');
insert into MOCK_DATA (id, course) values (545, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (546, 'Biostatistician I');
insert into MOCK_DATA (id, course) values (547, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (548, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (549, 'Financial Analyst');
insert into MOCK_DATA (id, course) values (550, 'Nurse Practicioner');
insert into MOCK_DATA (id, course) values (551, 'Librarian');
insert into MOCK_DATA (id, course) values (552, 'Staff Accountant II');
insert into MOCK_DATA (id, course) values (553, 'Administrative Assistant III');
insert into MOCK_DATA (id, course) values (554, 'Recruiter');
insert into MOCK_DATA (id, course) values (555, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (556, 'Assistant Professor');
insert into MOCK_DATA (id, course) values (557, 'Programmer Analyst IV');
insert into MOCK_DATA (id, course) values (558, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (559, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (560, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (561, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (562, 'Nurse Practicioner');
insert into MOCK_DATA (id, course) values (563, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (564, 'Office Assistant II');
insert into MOCK_DATA (id, course) values (565, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (566, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (567, 'Analyst Programmer');
insert into MOCK_DATA (id, course) values (568, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (569, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (570, 'Programmer IV');
insert into MOCK_DATA (id, course) values (571, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (572, 'Project Manager');
insert into MOCK_DATA (id, course) values (573, 'General Manager');
insert into MOCK_DATA (id, course) values (574, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (575, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (576, 'Staff Accountant I');
insert into MOCK_DATA (id, course) values (577, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (578, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (579, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (580, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (581, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (582, 'Senior Sales Associate');
insert into MOCK_DATA (id, course) values (583, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (584, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (585, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (586, 'Structural Analysis Engineer');
insert into MOCK_DATA (id, course) values (587, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (588, 'Senior Cost Accountant');
insert into MOCK_DATA (id, course) values (589, 'Engineer III');
insert into MOCK_DATA (id, course) values (590, 'Registered Nurse');
insert into MOCK_DATA (id, course) values (591, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (592, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (593, 'Compensation Analyst');
insert into MOCK_DATA (id, course) values (594, 'Engineer II');
insert into MOCK_DATA (id, course) values (595, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (596, 'Financial Analyst');
insert into MOCK_DATA (id, course) values (597, 'Computer Systems Analyst II');
insert into MOCK_DATA (id, course) values (598, 'VP Product Management');
insert into MOCK_DATA (id, course) values (599, 'Teacher');
insert into MOCK_DATA (id, course) values (600, 'Senior Editor');
insert into MOCK_DATA (id, course) values (601, 'Director of Sales');
insert into MOCK_DATA (id, course) values (602, 'Professor');
insert into MOCK_DATA (id, course) values (603, 'Pharmacist');
insert into MOCK_DATA (id, course) values (604, 'Sales Associate');
insert into MOCK_DATA (id, course) values (605, 'Accounting Assistant II');
insert into MOCK_DATA (id, course) values (606, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (607, 'Social Worker');
insert into MOCK_DATA (id, course) values (608, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (609, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (610, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (611, 'Editor');
insert into MOCK_DATA (id, course) values (612, 'Sales Representative');
insert into MOCK_DATA (id, course) values (613, 'Health Coach II');
insert into MOCK_DATA (id, course) values (614, 'VP Sales');
insert into MOCK_DATA (id, course) values (615, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (616, 'Media Manager IV');
insert into MOCK_DATA (id, course) values (617, 'Human Resources Assistant II');
insert into MOCK_DATA (id, course) values (618, 'Media Manager III');
insert into MOCK_DATA (id, course) values (619, 'Senior Cost Accountant');
insert into MOCK_DATA (id, course) values (620, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (621, 'General Manager');
insert into MOCK_DATA (id, course) values (622, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (623, 'Director of Sales');
insert into MOCK_DATA (id, course) values (624, 'Pharmacist');
insert into MOCK_DATA (id, course) values (625, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (626, 'Operator');
insert into MOCK_DATA (id, course) values (627, 'Quality Control Specialist');
insert into MOCK_DATA (id, course) values (628, 'Administrative Assistant III');
insert into MOCK_DATA (id, course) values (629, 'Nurse Practicioner');
insert into MOCK_DATA (id, course) values (630, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (631, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (632, 'Biostatistician I');
insert into MOCK_DATA (id, course) values (633, 'VP Accounting');
insert into MOCK_DATA (id, course) values (634, 'Web Developer I');
insert into MOCK_DATA (id, course) values (635, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (636, 'Health Coach III');
insert into MOCK_DATA (id, course) values (637, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (638, 'Sales Associate');
insert into MOCK_DATA (id, course) values (639, 'Tax Accountant');
insert into MOCK_DATA (id, course) values (640, 'Biostatistician IV');
insert into MOCK_DATA (id, course) values (641, 'Accountant IV');
insert into MOCK_DATA (id, course) values (642, 'Software Engineer II');
insert into MOCK_DATA (id, course) values (643, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (644, 'Editor');
insert into MOCK_DATA (id, course) values (645, 'Web Developer II');
insert into MOCK_DATA (id, course) values (646, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (647, 'VP Product Management');
insert into MOCK_DATA (id, course) values (648, 'Librarian');
insert into MOCK_DATA (id, course) values (649, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (650, 'Senior Editor');
insert into MOCK_DATA (id, course) values (651, 'Actuary');
insert into MOCK_DATA (id, course) values (652, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (653, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (654, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (655, 'Account Executive');
insert into MOCK_DATA (id, course) values (656, 'Technical Writer');
insert into MOCK_DATA (id, course) values (657, 'VP Marketing');
insert into MOCK_DATA (id, course) values (658, 'Systems Administrator II');
insert into MOCK_DATA (id, course) values (659, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (660, 'Engineer IV');
insert into MOCK_DATA (id, course) values (661, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (662, 'Sales Associate');
insert into MOCK_DATA (id, course) values (663, 'Senior Developer');
insert into MOCK_DATA (id, course) values (664, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (665, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (666, 'Software Test Engineer I');
insert into MOCK_DATA (id, course) values (667, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (668, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (669, 'Developer II');
insert into MOCK_DATA (id, course) values (670, 'Health Coach I');
insert into MOCK_DATA (id, course) values (671, 'Account Executive');
insert into MOCK_DATA (id, course) values (672, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (673, 'Teacher');
insert into MOCK_DATA (id, course) values (674, 'Tax Accountant');
insert into MOCK_DATA (id, course) values (675, 'Staff Accountant II');
insert into MOCK_DATA (id, course) values (676, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (677, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (678, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (679, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (680, 'Senior Editor');
insert into MOCK_DATA (id, course) values (681, 'Senior Developer');
insert into MOCK_DATA (id, course) values (682, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (683, 'VP Marketing');
insert into MOCK_DATA (id, course) values (684, 'Geologist I');
insert into MOCK_DATA (id, course) values (685, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (686, 'General Manager');
insert into MOCK_DATA (id, course) values (687, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (688, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (689, 'Social Worker');
insert into MOCK_DATA (id, course) values (690, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (691, 'Account Executive');
insert into MOCK_DATA (id, course) values (692, 'Safety Technician III');
insert into MOCK_DATA (id, course) values (693, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (694, 'Product Engineer');
insert into MOCK_DATA (id, course) values (695, 'Systems Administrator II');
insert into MOCK_DATA (id, course) values (696, 'Social Worker');
insert into MOCK_DATA (id, course) values (697, 'Developer IV');
insert into MOCK_DATA (id, course) values (698, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (699, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (700, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (701, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (702, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (703, 'Analyst Programmer');
insert into MOCK_DATA (id, course) values (704, 'Budget/Accounting Analyst III');
insert into MOCK_DATA (id, course) values (705, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (706, 'Software Engineer III');
insert into MOCK_DATA (id, course) values (707, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (708, 'Statistician II');
insert into MOCK_DATA (id, course) values (709, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (710, 'Office Assistant I');
insert into MOCK_DATA (id, course) values (711, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (712, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (713, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (714, 'Programmer IV');
insert into MOCK_DATA (id, course) values (715, 'Structural Analysis Engineer');
insert into MOCK_DATA (id, course) values (716, 'Web Designer IV');
insert into MOCK_DATA (id, course) values (717, 'Sales Representative');
insert into MOCK_DATA (id, course) values (718, 'Staff Accountant II');
insert into MOCK_DATA (id, course) values (719, 'Nurse');
insert into MOCK_DATA (id, course) values (720, 'Design Engineer');
insert into MOCK_DATA (id, course) values (721, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (722, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (723, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (724, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (725, 'Director of Sales');
insert into MOCK_DATA (id, course) values (726, 'Programmer Analyst III');
insert into MOCK_DATA (id, course) values (727, 'Research Associate');
insert into MOCK_DATA (id, course) values (728, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (729, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (730, 'Senior Editor');
insert into MOCK_DATA (id, course) values (731, 'Health Coach I');
insert into MOCK_DATA (id, course) values (732, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (733, 'Web Designer II');
insert into MOCK_DATA (id, course) values (734, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (735, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (736, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (737, 'Technical Writer');
insert into MOCK_DATA (id, course) values (738, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (739, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (740, 'Administrative Assistant III');
insert into MOCK_DATA (id, course) values (741, 'Account Representative IV');
insert into MOCK_DATA (id, course) values (742, 'Accountant I');
insert into MOCK_DATA (id, course) values (743, 'Sales Associate');
insert into MOCK_DATA (id, course) values (744, 'Actuary');
insert into MOCK_DATA (id, course) values (745, 'Director of Sales');
insert into MOCK_DATA (id, course) values (746, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (747, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (748, 'Associate Professor');
insert into MOCK_DATA (id, course) values (749, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (750, 'Operator');
insert into MOCK_DATA (id, course) values (751, 'Senior Cost Accountant');
insert into MOCK_DATA (id, course) values (752, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (753, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (754, 'Speech Pathologist');
insert into MOCK_DATA (id, course) values (755, 'Computer Systems Analyst I');
insert into MOCK_DATA (id, course) values (756, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (757, 'Engineer III');
insert into MOCK_DATA (id, course) values (758, 'Geologist IV');
insert into MOCK_DATA (id, course) values (759, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (760, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (761, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (762, 'Web Developer IV');
insert into MOCK_DATA (id, course) values (763, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (764, 'Geologist IV');
insert into MOCK_DATA (id, course) values (765, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (766, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (767, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (768, 'Senior Editor');
insert into MOCK_DATA (id, course) values (769, 'Programmer Analyst III');
insert into MOCK_DATA (id, course) values (770, 'Office Assistant III');
insert into MOCK_DATA (id, course) values (771, 'Compensation Analyst');
insert into MOCK_DATA (id, course) values (772, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (773, 'Biostatistician III');
insert into MOCK_DATA (id, course) values (774, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (775, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (776, 'Accountant II');
insert into MOCK_DATA (id, course) values (777, 'Recruiter');
insert into MOCK_DATA (id, course) values (778, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (779, 'Compensation Analyst');
insert into MOCK_DATA (id, course) values (780, 'VP Sales');
insert into MOCK_DATA (id, course) values (781, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (782, 'Teacher');
insert into MOCK_DATA (id, course) values (783, 'Physical Therapy Assistant');
insert into MOCK_DATA (id, course) values (784, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (785, 'Sales Associate');
insert into MOCK_DATA (id, course) values (786, 'Systems Administrator IV');
insert into MOCK_DATA (id, course) values (787, 'Internal Auditor');
insert into MOCK_DATA (id, course) values (788, 'Administrative Assistant I');
insert into MOCK_DATA (id, course) values (789, 'Account Executive');
insert into MOCK_DATA (id, course) values (790, 'Associate Professor');
insert into MOCK_DATA (id, course) values (791, 'Technical Writer');
insert into MOCK_DATA (id, course) values (792, 'Executive Secretary');
insert into MOCK_DATA (id, course) values (793, 'VP Accounting');
insert into MOCK_DATA (id, course) values (794, 'Research Associate');
insert into MOCK_DATA (id, course) values (795, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (796, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (797, 'Geologist II');
insert into MOCK_DATA (id, course) values (798, 'Civil Engineer');
insert into MOCK_DATA (id, course) values (799, 'Computer Systems Analyst I');
insert into MOCK_DATA (id, course) values (800, 'Nurse');
insert into MOCK_DATA (id, course) values (801, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (802, 'Health Coach IV');
insert into MOCK_DATA (id, course) values (803, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (804, 'VP Sales');
insert into MOCK_DATA (id, course) values (805, 'Biostatistician IV');
insert into MOCK_DATA (id, course) values (806, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (807, 'Nurse');
insert into MOCK_DATA (id, course) values (808, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (809, 'Human Resources Assistant III');
insert into MOCK_DATA (id, course) values (810, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (811, 'Web Designer II');
insert into MOCK_DATA (id, course) values (812, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (813, 'Senior Developer');
insert into MOCK_DATA (id, course) values (814, 'Programmer I');
insert into MOCK_DATA (id, course) values (815, 'Nurse');
insert into MOCK_DATA (id, course) values (816, 'Quality Engineer');
insert into MOCK_DATA (id, course) values (817, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (818, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (819, 'Design Engineer');
insert into MOCK_DATA (id, course) values (820, 'GIS Technical Architect');
insert into MOCK_DATA (id, course) values (821, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (822, 'Nuclear Power Engineer');
insert into MOCK_DATA (id, course) values (823, 'Help Desk Operator');
insert into MOCK_DATA (id, course) values (824, 'Developer I');
insert into MOCK_DATA (id, course) values (825, 'Account Executive');
insert into MOCK_DATA (id, course) values (826, 'Senior Sales Associate');
insert into MOCK_DATA (id, course) values (827, 'Pharmacist');
insert into MOCK_DATA (id, course) values (828, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (829, 'Structural Engineer');
insert into MOCK_DATA (id, course) values (830, 'Statistician IV');
insert into MOCK_DATA (id, course) values (831, 'Human Resources Manager');
insert into MOCK_DATA (id, course) values (832, 'Programmer Analyst IV');
insert into MOCK_DATA (id, course) values (833, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (834, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (835, 'Statistician I');
insert into MOCK_DATA (id, course) values (836, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (837, 'Research Assistant I');
insert into MOCK_DATA (id, course) values (838, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (839, 'Assistant Media Planner');
insert into MOCK_DATA (id, course) values (840, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (841, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (842, 'Nurse');
insert into MOCK_DATA (id, course) values (843, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (844, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (845, 'Product Engineer');
insert into MOCK_DATA (id, course) values (846, 'Recruiter');
insert into MOCK_DATA (id, course) values (847, 'Legal Assistant');
insert into MOCK_DATA (id, course) values (848, 'Food Chemist');
insert into MOCK_DATA (id, course) values (849, 'Statistician I');
insert into MOCK_DATA (id, course) values (850, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (851, 'Occupational Therapist');
insert into MOCK_DATA (id, course) values (852, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (853, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (854, 'Junior Executive');
insert into MOCK_DATA (id, course) values (855, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (856, 'Electrical Engineer');
insert into MOCK_DATA (id, course) values (857, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (858, 'Project Manager');
insert into MOCK_DATA (id, course) values (859, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (860, 'Accounting Assistant IV');
insert into MOCK_DATA (id, course) values (861, 'Senior Developer');
insert into MOCK_DATA (id, course) values (862, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (863, 'Associate Professor');
insert into MOCK_DATA (id, course) values (864, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (865, 'Junior Executive');
insert into MOCK_DATA (id, course) values (866, 'Mechanical Systems Engineer');
insert into MOCK_DATA (id, course) values (867, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (868, 'Editor');
insert into MOCK_DATA (id, course) values (869, 'Occupational Therapist');
insert into MOCK_DATA (id, course) values (870, 'Systems Administrator II');
insert into MOCK_DATA (id, course) values (871, 'Community Outreach Specialist');
insert into MOCK_DATA (id, course) values (872, 'Web Designer II');
insert into MOCK_DATA (id, course) values (873, 'Junior Executive');
insert into MOCK_DATA (id, course) values (874, 'Systems Administrator III');
insert into MOCK_DATA (id, course) values (875, 'Budget/Accounting Analyst IV');
insert into MOCK_DATA (id, course) values (876, 'Cost Accountant');
insert into MOCK_DATA (id, course) values (877, 'Engineer I');
insert into MOCK_DATA (id, course) values (878, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (879, 'Desktop Support Technician');
insert into MOCK_DATA (id, course) values (880, 'Marketing Assistant');
insert into MOCK_DATA (id, course) values (881, 'Quality Engineer');
insert into MOCK_DATA (id, course) values (882, 'Geologist III');
insert into MOCK_DATA (id, course) values (883, 'Programmer Analyst I');
insert into MOCK_DATA (id, course) values (884, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (885, 'Social Worker');
insert into MOCK_DATA (id, course) values (886, 'Senior Developer');
insert into MOCK_DATA (id, course) values (887, 'Pharmacist');
insert into MOCK_DATA (id, course) values (888, 'Engineer IV');
insert into MOCK_DATA (id, course) values (889, 'Technical Writer');
insert into MOCK_DATA (id, course) values (890, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (891, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (892, 'Senior Developer');
insert into MOCK_DATA (id, course) values (893, 'Health Coach IV');
insert into MOCK_DATA (id, course) values (894, 'Structural Engineer');
insert into MOCK_DATA (id, course) values (895, 'Budget/Accounting Analyst IV');
insert into MOCK_DATA (id, course) values (896, 'Statistician I');
insert into MOCK_DATA (id, course) values (897, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (898, 'Paralegal');
insert into MOCK_DATA (id, course) values (899, 'Programmer III');
insert into MOCK_DATA (id, course) values (900, 'Research Associate');
insert into MOCK_DATA (id, course) values (901, 'Administrative Officer');
insert into MOCK_DATA (id, course) values (902, 'Database Administrator IV');
insert into MOCK_DATA (id, course) values (903, 'Design Engineer');
insert into MOCK_DATA (id, course) values (904, 'Senior Developer');
insert into MOCK_DATA (id, course) values (905, 'Safety Technician IV');
insert into MOCK_DATA (id, course) values (906, 'Statistician IV');
insert into MOCK_DATA (id, course) values (907, 'Assistant Manager');
insert into MOCK_DATA (id, course) values (908, 'Programmer Analyst III');
insert into MOCK_DATA (id, course) values (909, 'Research Associate');
insert into MOCK_DATA (id, course) values (910, 'Clinical Specialist');
insert into MOCK_DATA (id, course) values (911, 'Sales Associate');
insert into MOCK_DATA (id, course) values (912, 'VP Marketing');
insert into MOCK_DATA (id, course) values (913, 'Software Engineer III');
insert into MOCK_DATA (id, course) values (914, 'Associate Professor');
insert into MOCK_DATA (id, course) values (915, 'Sales Associate');
insert into MOCK_DATA (id, course) values (916, 'Budget/Accounting Analyst IV');
insert into MOCK_DATA (id, course) values (917, 'Social Worker');
insert into MOCK_DATA (id, course) values (918, 'Health Coach III');
insert into MOCK_DATA (id, course) values (919, 'Safety Technician II');
insert into MOCK_DATA (id, course) values (920, 'Food Chemist');
insert into MOCK_DATA (id, course) values (921, 'Staff Accountant III');
insert into MOCK_DATA (id, course) values (922, 'Sales Associate');
insert into MOCK_DATA (id, course) values (923, 'Account Executive');
insert into MOCK_DATA (id, course) values (924, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (925, 'Chief Design Engineer');
insert into MOCK_DATA (id, course) values (926, 'Analyst Programmer');
insert into MOCK_DATA (id, course) values (927, 'Junior Executive');
insert into MOCK_DATA (id, course) values (928, 'Teacher');
insert into MOCK_DATA (id, course) values (929, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (930, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (931, 'Paralegal');
insert into MOCK_DATA (id, course) values (932, 'Project Manager');
insert into MOCK_DATA (id, course) values (933, 'Nurse Practicioner');
insert into MOCK_DATA (id, course) values (934, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (935, 'Graphic Designer');
insert into MOCK_DATA (id, course) values (936, 'Information Systems Manager');
insert into MOCK_DATA (id, course) values (937, 'Editor');
insert into MOCK_DATA (id, course) values (938, 'Civil Engineer');
insert into MOCK_DATA (id, course) values (939, 'Librarian');
insert into MOCK_DATA (id, course) values (940, 'Senior Cost Accountant');
insert into MOCK_DATA (id, course) values (941, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (942, 'Account Representative IV');
insert into MOCK_DATA (id, course) values (943, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (944, 'Recruiting Manager');
insert into MOCK_DATA (id, course) values (945, 'VP Product Management');
insert into MOCK_DATA (id, course) values (946, 'Pharmacist');
insert into MOCK_DATA (id, course) values (947, 'Data Coordiator');
insert into MOCK_DATA (id, course) values (948, 'Product Engineer');
insert into MOCK_DATA (id, course) values (949, 'Research Associate');
insert into MOCK_DATA (id, course) values (950, 'Systems Administrator II');
insert into MOCK_DATA (id, course) values (951, 'Automation Specialist III');
insert into MOCK_DATA (id, course) values (952, 'Civil Engineer');
insert into MOCK_DATA (id, course) values (953, 'Accountant II');
insert into MOCK_DATA (id, course) values (954, 'Paralegal');
insert into MOCK_DATA (id, course) values (955, 'Software Consultant');
insert into MOCK_DATA (id, course) values (956, 'Staff Scientist');
insert into MOCK_DATA (id, course) values (957, 'Business Systems Development Analyst');
insert into MOCK_DATA (id, course) values (958, 'Social Worker');
insert into MOCK_DATA (id, course) values (959, 'Pharmacist');
insert into MOCK_DATA (id, course) values (960, 'Teacher');
insert into MOCK_DATA (id, course) values (961, 'Paralegal');
insert into MOCK_DATA (id, course) values (962, 'Senior Developer');
insert into MOCK_DATA (id, course) values (963, 'Technical Writer');
insert into MOCK_DATA (id, course) values (964, 'Actuary');
insert into MOCK_DATA (id, course) values (965, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (966, 'VP Accounting');
insert into MOCK_DATA (id, course) values (967, 'Design Engineer');
insert into MOCK_DATA (id, course) values (968, 'Systems Administrator I');
insert into MOCK_DATA (id, course) values (969, 'Financial Advisor');
insert into MOCK_DATA (id, course) values (970, 'Engineer I');
insert into MOCK_DATA (id, course) values (971, 'VP Marketing');
insert into MOCK_DATA (id, course) values (972, 'Dental Hygienist');
insert into MOCK_DATA (id, course) values (973, 'Office Assistant IV');
insert into MOCK_DATA (id, course) values (974, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (975, 'Geological Engineer');
insert into MOCK_DATA (id, course) values (976, 'Analog Circuit Design manager');
insert into MOCK_DATA (id, course) values (977, 'Marketing Manager');
insert into MOCK_DATA (id, course) values (978, 'VP Sales');
insert into MOCK_DATA (id, course) values (979, 'Accountant IV');
insert into MOCK_DATA (id, course) values (980, 'VP Quality Control');
insert into MOCK_DATA (id, course) values (981, 'Accountant II');
insert into MOCK_DATA (id, course) values (982, 'Help Desk Technician');
insert into MOCK_DATA (id, course) values (983, 'Research Nurse');
insert into MOCK_DATA (id, course) values (984, 'Senior Sales Associate');
insert into MOCK_DATA (id, course) values (985, 'Environmental Tech');
insert into MOCK_DATA (id, course) values (986, 'Professor');
insert into MOCK_DATA (id, course) values (987, 'Payment Adjustment Coordinator');
insert into MOCK_DATA (id, course) values (988, 'Research Associate');
insert into MOCK_DATA (id, course) values (989, 'Database Administrator IV');
insert into MOCK_DATA (id, course) values (990, 'Systems Administrator I');
insert into MOCK_DATA (id, course) values (991, 'Environmental Specialist');
insert into MOCK_DATA (id, course) values (992, 'Senior Developer');
insert into MOCK_DATA (id, course) values (993, 'Senior Quality Engineer');
insert into MOCK_DATA (id, course) values (994, 'Teacher');
insert into MOCK_DATA (id, course) values (995, 'Chemical Engineer');
insert into MOCK_DATA (id, course) values (996, 'Engineer II');
insert into MOCK_DATA (id, course) values (997, 'Senior Financial Analyst');
insert into MOCK_DATA (id, course) values (998, 'Account Executive');
insert into MOCK_DATA (id, course) values (999, 'Nurse');
insert into MOCK_DATA (id, course) values (1000, 'Account Representative II');
